T_var:
  Topt: 18

dht22:
  pin: 27

log:
  directory: "/Users/theo/Desktop/test/"
  filename: "gpio_controller.log"
  level: "INFO"

config_reload_interval: 4   # secondi

gpio_pins:
  - name: "AEROPONICS"
    pin: 17
    interval: 3
    on_time: 10

  - name: "IDROPONICS"
    pin_pump: 27
    pin_sensor: 15
    interval: 2
    on_time: 20


