T_var:
  Topt: 18

dht22:
  pin: 23

log:
  directory: "/home/fishnplants/Desktop/"
  filename: "FnP_AeroGreenHouse.log"
  level: "INFO"

config_reload_interval: 4   # secondi

gpio_pins:
  - name: "AEROPONICS"
    pin: 17
    what_type: "pump"
    interval: 8
    on_time: 3

  - name: "IDROPONICS"
    pin: 27
    what_type: "pump"
    interval: 6
    on_time: 2

  - name: "MOISTURE"
    pin: 13
    what_type: "sensor"


