T_var:
  Topt: 18

log:
  directory: "./logs"
  filename: "gpio_controller.log"
  level: "INFO"

config_reload_interval: 5   # secondi

gpio_pins:
  - name: "AEROPONICS"
    pin: 17
    interval: 60
    on_time: 10

  - name: "IDROPONICS"
    pin: 27
    interval: 120
    on_time: 20
