T_var:
  Topt: 18.0

dht22:
  pin: 23
  read_interval: 5
  save : True
  saving_dir : /home/fishnplants/Desktop/data/TH/

log:
  directory: /home/fishnplants/Desktop/
  filename: FnP_AeroGreenHouse
  level: INFO

config_reload_interval: 4

gpio_pins:
- name: AEROPONICS
  pin: 15
  what_type: pump
  interval: 8
  on_time: 3
- name: IDROPONICS
  pin: 27
  what_type: pump
  interval: 2
  on_time: 5
- name: MOISTURE
  pin: 13
  what_type: sensor
